version: "3.0"

services:
        gogs:
                image: "gogs/gogs"
                ports:
                        - "3000:3000"
                        - "10022:22"
                volumes:
                        - /root/Documents/docker/gogs/data:/data
                restart: always
                depends_on:
                        - gogs_db

        gogs_db:
                image: postgres
                environment:
                        - POSTGRES_PASSWORD=gogs_password
                        - POSTGRES_USER=gogs
                        - POSTGRES_DB=gogs_db
                volumes:
                        - /root/Documents/docker/gogs/gogs_db:/var/lib/postgresql/data